### PR TITLE
Use builder generics as intended

### PR DESCRIPTION
**Pull request by arielmelendez**

### CODE REVIEW

**Review by fedellen — APPROVED** [review]

**Review by matibat — APPROVED** [review]
Looks good to me!

**Review by fedellen — CHANGES_REQUESTED** [review]
Currently has conflicts. We're working a couple bugs out in the list folder branch. Once thats settled we'll work on the conflicts and get this merged up.

**Comment by matibat** [comment]
Added a merge commit for fixing the conflicts with the base

**Review by matibat — APPROVED** [review]
LGTM

**Comment by fedellen** [comment]
Merge conflicts are resolved, but the `list_folder` command does not seem work on this branch yet. 

`(node:42639) UnhandledPromiseRejectionWarning: Error: Invalid folder state` on both private and public commands

I'll dig around to find the cause.

**Comment by fedellen** [comment]
> (node:42639) UnhandledPromiseRejectionWarning: Error: Invalid folder state on both private and public commands

We needed to account for the root folder of a drive, which does not include the `Parent-Folder-Id` tag.

Fixed here: 3ccf613

The `list-folder` and `folder-info` commands are now functional here!

**Review by fedellen — APPROVED** [review]
Looks good to me now!

**Pull request merged**
